//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dirico_assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Variants = new HashSet<Variant>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public int AssetTypeId { get; set; }
        public int FileObjectId { get; set; }
        public string BlobName { get; set; }
        public string BlobPath { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<long> Size { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual FolderStructure FolderStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variant> Variants { get; set; }
    }
}
