//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dirico_assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public int ID { get; set; }
        public int FileObjectId { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string AssetMetaData { get; set; }
        public string Properties { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual FolderStructure FolderStructure { get; set; }
    }
}
